const TYPE_SCALAR_MAP = Object.freeze({
  STRING: "string",
  TEXT: "string",
  INTEGER: "number",
  BIGINT: "number",
  FLOAT: "number",
  DOUBLE: "number",
  DECIMAL: "number",
  BOOLEAN: "boolean",
  DATE: "string",
  DATEONLY: "string",
  JSON: "Record<string, unknown>",
  JSONB: "Record<string, unknown>",
  OBJECT: "Record<string, unknown>",
});

export function generateType(change, currentSchema) {
  assertChange(change);
  assertSchema(currentSchema);
  const merged = mergeFields(currentSchema.fields, change);
  const lines = [
    `// auto-generated by services/codegen/src/frontendGenerators.js`,
    `// model=${change.model} schemaChange.field=${change.field} type=${change.type}`,
    ``,
    `export interface ${change.model} {`,
  ];
  for (const field of merged) {
    lines.push(`  ${field.name}: ${mapType(field.type)};`);
  }
  lines.push(`}`, ``);
  return lines.join("\n");
}

export function generateServiceStub(change) {
  assertChange(change);
  const plural = pluralize(change.model);
  const fieldPascal = capitalize(change.field);
  return [
    `// auto-generated by services/codegen/src/frontendGenerators.js`,
    `// model=${change.model} field=${change.field} type=${change.type}`,
    ``,
    `export async function get${change.model}List() {`,
    `  const res = await fetch("/api/${plural}");`,
    `  if (!res.ok) throw new Error("Failed to fetch ${plural}: " + res.status);`,
    `  return res.json();`,
    `}`,
    ``,
    `export async function update${change.model}${fieldPascal}(slug, value) {`,
    `  const res = await fetch(\`/api/${plural}/\${slug}\`, {`,
    `    method: "PATCH",`,
    `    headers: { "Content-Type": "application/json" },`,
    `    body: JSON.stringify({ ${change.field}: value }),`,
    `  });`,
    `  if (!res.ok) throw new Error("Failed to update ${change.model}.${change.field}: " + res.status);`,
    `  return res.json();`,
    `}`,
    ``,
  ].join("\n");
}

export function generateMock(change) {
  assertChange(change);
  const plural = pluralize(change.model);
  const mockExport = `mock${capitalize(plural)}`;
  return [
    `// auto-generated by services/codegen/src/frontendGenerators.js`,
    `// model=${change.model} field=${change.field} type=${change.type}`,
    ``,
    `export const ${mockExport} = [`,
    `  { slug: "auto-1", ${change.field}: ${mockValue(change.type, 1)} },`,
    `  { slug: "auto-2", ${change.field}: ${mockValue(change.type, 2)} },`,
    `];`,
    ``,
  ].join("\n");
}

export function generateAll(change, currentSchema) {
  return Object.freeze({
    type: generateType(change, currentSchema),
    serviceStub: generateServiceStub(change),
    mock: generateMock(change),
  });
}

function mergeFields(existing, change) {
  if (change.op === "remove") {
    return existing.filter((field) => field.name !== change.field);
  }
  const others = existing.filter((field) => field.name !== change.field);
  return [...others, { name: change.field, type: change.type }];
}

function mapType(sequelizeType) {
  return TYPE_SCALAR_MAP[sequelizeType] ?? "unknown";
}

function mockValue(sequelizeType, index) {
  const target = TYPE_SCALAR_MAP[sequelizeType] ?? "unknown";
  if (target === "string") return JSON.stringify(`mock-${index}`);
  if (target === "number") return String(index);
  if (target === "boolean") return index % 2 === 0 ? "false" : "true";
  return "null";
}

function pluralize(model) {
  return `${model.toLowerCase()}s`;
}

function capitalize(value) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function assertChange(change) {
  if (!change || typeof change !== "object") {
    throw new Error("frontendGenerators: change must be an object");
  }
  for (const key of ["model", "field", "type", "op"]) {
    if (typeof change[key] !== "string" || !change[key].trim()) {
      throw new Error(`frontendGenerators: change.${key} must be a non-empty string`);
    }
  }
}

function assertSchema(schema) {
  if (!schema || !Array.isArray(schema.fields)) {
    throw new Error("frontendGenerators: schema.fields must be an array");
  }
}
